# Generated by Django 4.2.1 on 2023-05-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jservice_id', models.IntegerField(unique=True)),
                ('answer', models.TextField()),
                ('question', models.TextField()),
                ('question_created_at', models.DateTimeField()),
            ],
        ),
    ]
